### ISSUE TITLE
Error: Write failed when script is ran on CachyOS

### ISSUE THREAD

**Issue by tedonporter** [maximmaxim345/yoga_pro_9i_gen9_linux#5]
Laptop: Yoga Pro 9i 16IMH9 (GEN 9)
OS: Cachy OS (Fresh Install)

I have used the audio fix on multiple distros and it has worked flawlessly until trying it on a fresh install of CachyOS.

- `i2c-tools` were pre-installed and up to date.
- 2pa-byps.sh script is located in `/usr/local/bin/` and made executable
- `yoga-16imh9-speakers.service` was created and located in `/etc/systemd/system/`

When running the systemctl commands to start and enable the service no errors are thrown but audio is not corrected.

When running the script manually I get the following output:

```
[krakkn@cachyos-yp9 ~]$ sudo /usr/local/bin/2pa-byps.sh 2

i2c bus is 2
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
Error: Write failed
```

Current status of the service:

```
[krakkn@cachyos-yp9 ~]$ systemctl status yoga-16imh9-speakers.service
○ yoga-16imh9-speakers.service - Turn on speakers using i2c configuration
     Loaded: loaded (/etc/systemd/system/yoga-16imh9-speakers.service; enabled; preset: disabled)
     Active: inactive (dead) since Sat 2024-07-06 01:38:42 EDT; 28min ago
 Invocation: ac74fc08c3ab4d459e26e80bd6b44f10
    Process: 2851 ExecStart=/bin/sh -c /usr/local/bin/2pa-byps.sh 2 | logger (code=exited, status=0/SUCCESS)
   Main PID: 2851 (code=exited, status=0/SUCCESS)

Jul 06 01:38:41 cachyos-yp9 sh[2925]: Error: Write failed
Jul 06 01:38:42 cachyos-yp9 sh[2926]: Error: Write failed
Jul 06 01:38:42 cachyos-yp9 sh[2927]: Error: Write failed
Jul 06 01:38:42 cachyos-yp9 sh[2928]: Error: Write failed
Jul 06 01:38:42 cachyos-yp9 sh[2929]: stty: 'standard input': Inappropriate ioctl for device
Jul 06 01:38:42 cachyos-yp9 sh[2930]: stty: 'standard input': Inappropriate ioctl for device
Jul 06 01:38:42 cachyos-yp9 sh[2931]: stty: invalid argument ‘’
Jul 06 01:38:42 cachyos-yp9 sh[2931]: Try 'stty --help' for more information.
Jul 06 01:38:42 cachyos-yp9 systemd[1]: yoga-16imh9-speakers.service: Deactivated successfully.
Jul 06 01:38:42 cachyos-yp9 systemd[1]: Finished Turn on speakers using i2c configuration.
```

Not sure what the issue is as every other distro has worked flawlessly with the fix. The only difference I can think of is that the default shell on CachyOS is fish so I had to `/bin/bash` to copy/execute the commands. I also did a diff check between my local files and the source and they are correct.

Let me know if any other logs are need. Thank you.

**Comment by maximmaxim345** [comment]
Can you try replacing:
#!/bin/bash
With:
#!/usr/bin/bash

And also replace:
ExecStart=/bin/sh -c "/usr/local/bin/2pa-byps.sh 2 | logger"
With:
ExecStart=/usr/bin/bash -c "/usr/local/bin/2pa-byps.sh 2 | logger"

In the service file.

Please let me know if this fixes the issue.

**Comment by tedonporter** [comment]
After making the changes and restarting the service still same results. Also tried doing a full system restart and same thing. You can see from the output below it is using `bash` instead of `sh`.

```
[krakkn@cachyos-yp9 ~]$ sudo systemctl status yoga-16imh9-speakers.service
○ yoga-16imh9-speakers.service - Turn on speakers using i2c configuration
     Loaded: loaded (/etc/systemd/system/yoga-16imh9-speakers.service; enabled; preset: disabled)
     Active: inactive (dead) since Sat 2024-07-06 03:05:01 EDT; 1min 52s ago
 Invocation: 785f7b65780c47099cb22198cd02094d
    Process: 2109 ExecStart=/usr/bin/bash -c /usr/local/bin/2pa-byps.sh 2 | logger (code=exited, s>
   Main PID: 2109 (code=exited, status=0/SUCCESS)

Jul 06 03:05:01 cachyos-yp9 bash[2183]: Error: Write failed
Jul 06 03:05:01 cachyos-yp9 bash[2184]: Error: Write failed
Jul 06 03:05:01 cachyos-yp9 bash[2185]: Error: Write failed
Jul 06 03:05:01 cachyos-yp9 bash[2186]: Error: Write failed
Jul 06 03:05:01 cachyos-yp9 bash[2187]: stty: 'standard input': Inappropriate ioctl for device
Jul 06 03:05:01 cachyos-yp9 bash[2188]: stty: 'standard input': Inappropriate ioctl for device
Jul 06 03:05:01 cachyos-yp9 bash[2189]: stty: invalid argument ‘’
Jul 06 03:05:01 cachyos-yp9 bash[2189]: Try 'stty --help' for more information.
Jul 06 03:05:01 cachyos-yp9 systemd[1]: yoga-16imh9-speakers.service: Deactivated successfully.
Jul 06 03:05:01 cachyos-yp9 systemd[1]: Finished Turn on speakers using i2c configuration.
```

I am wondering if it is a permission issue or possibly an issue with fish being the default shell. I did find some information at the following link regarding the `ioctl` error referenced in the systemctl status output so I am going to try reverting the changes in the files back to original and then set my default shell to bash and reboot and see if that makes a difference. I'll report back soon.

**Comment by tedonporter** [comment]
So no dice. I don't think the service file is the issue as running the script directly just gives write errors so maybe the issue is with permissions on the files it is trying to write to. Could try removing i2c-tools completely, rebooting and then reinstalling.

**Comment by maximmaxim345** [comment]
So it's probably not fish that causes the problem. I don't know about cachyos, so i don't know if it has apparmor or selinux.
If it has any of them, try disabling them with:
sudo systemctl stop apparmor
And:
sude setenforce 0

Than without a reboot try restarting the speaker service.

**Comment by maximmaxim345** [comment]
Ok, I just tried on Arch linux. Has the same problem. Will let you know if i find something.

**Comment by maximmaxim345** [comment]
Can you try the updated instructions? If they work, you can close this issue.

**Comment by Dirtyjimmy** [comment]
Tested CachyOS a few weeks ago and tested out different kernel builds. The right i2c bus number was switching between the numbers 0, 2, 3 and 17 for some reason.

**Comment by tedonporter** [comment]
> Can you try the updated instructions? If they work, you can close this issue.

I used the updated scripts you provided on the repo and it appears that by removing the fixed 2 selection in the script has corrected the issue. Apparently 19 was chosen for this particular install.

`Jul 06 17:49:25 cachyos-yp9 root[3042]: Using I2C bus: 19`


Full Output:
```
[krakkn@cachyos-yp9 ~]$ systemctl status yoga-16imh9-speakers.service
○ yoga-16imh9-speakers.service - Turn on speakers using i2c configuration
     Loaded: loaded (/etc/systemd/system/yoga-16imh9-speakers.service; enabled; preset: disabled)
     Active: inactive (dead) since Sat 2024-07-06 17:49:25 EDT; 2min 15s ago
 Invocation: ba95b1e935b340a797639245ad2c2aeb
   Main PID: 3040 (code=exited, status=0/SUCCESS)

Jul 06 17:49:24 cachyos-yp9 systemd[1]: Starting Turn on speakers using i2c configuration...
Jul 06 17:49:25 cachyos-yp9 sh[3043]: TERM environment variable not set.
Jul 06 17:49:25 cachyos-yp9 root[3042]: Using I2C bus: 19
Jul 06 17:49:25 cachyos-yp9 sh[3128]: stty: 'standard input': Inappropriate ioctl for device
Jul 06 17:49:25 cachyos-yp9 sh[3129]: stty: 'standard input': Inappropriate ioctl for device
Jul 06 17:49:25 cachyos-yp9 sh[3130]: stty: invalid argument ‘’
Jul 06 17:49:25 cachyos-yp9 sh[3130]: Try 'stty --help' for more information.
Jul 06 17:49:25 cachyos-yp9 systemd[1]: yoga-16imh9-speakers.service: Deactivated successfully.
Jul 06 17:49:25 cachyos-yp9 systemd[1]: Finished Turn on speakers using i2c configuration.
```

**Comment by tedonporter** [comment]
Using updated scripts has corrected the issue. Resolved.
