### ISSUE TITLE
Display might be fixed with new drm i915 driver

### ISSUE THREAD

**Issue by rtoscanelli** [maximmaxim345/yoga_pro_9i_gen9_linux#6]
Hi!
I have this laptop and I was talking in reddit about the displays issues and one redditor did this and reported that the displays problems might be fixable with the [new intel drivers](https://www.reddit.com/r/Lenovo/comments/1d28fhl/comment/lbsj89k/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) even [without an ICC](https://www.reddit.com/r/Lenovo/comments/1d28fhl/comment/lbsm4f9/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button).
I recommend you to take a look on that discussion.

**Comment by maximmaxim345** [comment]
That's actually my reddit post! I'm currently running GNOME right now. Thanks for reminding me to update this readme. I will do that as soon as I find some time.
