### ISSUE TITLE
Thanks! Great fix for sound issues

### ISSUE THREAD

**Issue by pacharanero** [maximmaxim345/yoga_pro_9i_gen9_linux#9]
Hi @maximmaxim345 - sorry to create an issue for this but wanted to say THANKS - the instructions in https://github.com/maximmaxim345/yoga_pro_9i_gen9_linux?tab=readme-ov-file#speakers worked perfectly, copied and pasted into the terminal. I had been experimenting with my own way to do it and used scripts from elsewhere, but your series of instructions, which include auto-finding the I2C bus number and creating a systemd service, were superior. Sound is fixed across reboots.

(I'm now on kernel 6.9.12 but it doesn't seem to be fixed yet....)

Anyway - thanks and feel free to delete this issue once read.

**Comment by maximmaxim345** [comment]
You're welcome!
I'm glad the instructions were helpful. Feel free to reach out if you have any other questions or issues.
